Feature/chat image support
jahwag/ClaudeSync pull request #79
Opened 2024-10-14 21:36 UTC by TweededBadger

This PR adds support for images in chat messages.

Example command:

`claudsync chat message --chat {chat-id} --image test.jpg "{chat-message}"`

2024-10-16 15:54 UTC, jahwag requested changes
Looks good, works well!

Some small details improvements/questions for you.

Please bump version in pyproject.toml to prep release 0.6.2.

2024-10-16 15:54 UTC, jahwag commented on src/claudesync/providers/claude_ai.py
> +            'Cookie': f'sessionKey={self.config.get_session_key("claude.ai")[0]}'
would you mind assigning this variable?

2024-10-16 15:54 UTC, jahwag commented on src/claudesync/providers/claude_ai.py
> +            'anthropic-client-sha': 'unknown',
are these two anthropic headers needed?

2024-10-24 09:14 UTC, wjutsum commented on src/claudesync/providers/claude_ai.py
> +            'Cookie': f'sessionKey={self.config.get_session_key("claude.ai")[0]}'
Done

2024-10-24 09:14 UTC, wjutsum commented on src/claudesync/providers/claude_ai.py
> +            'anthropic-client-sha': 'unknown',
Done

2024-10-24 09:16 UTC, wjutsum commented
Commenting to remove stale flag

2024-10-26 08:06 UTC, jahwag requested changes
this branch is behind master (0.6.2) and needs to be rebased and version bumped

2024-11-01 12:46 UTC, wjutsum commented
> this branch is behind master (0.6.2) and needs to be rebased and version bumped

That's done @jahwag

2024-11-29 02:47 UTC, closed without merging